### ISSUE TITLE
Unexpected fields appearing: "indexed as type text" etc

### ISSUE THREAD

**Issue by sylus** [dcameron/search_api_solr_datasource#8]
Hi there! 

I mentioned this issue earlier over in the other issue queue but thought I would file it as a separate issue here and see what you think might be the culprit.

If you look at the attached image sometimes I am getting weird field values displayed with results such as: "ss_ati_year_en [ss_ati_year_en]: indexed as type text (boost 1)" and in no particular order?

It was discussed that this might be because when the fields are empty the __toString() method is still being invoked, but when I check my fields returned back from solr they are all present so I am not really sure how these entries are occuring. ^_^

![unexpected_fields](https://cloud.githubusercontent.com/assets/984304/25645681/94a376ce-2f7e-11e7-9374-3059ba99aef2.png)

Thanks again for the amazing module port though! Aside from this small issue everything is working rather well :)

**Comment by DavidACameron-USDA** [comment]
Ok, yeah.  It's totally weird that those fields seem to be displayed correctly on some rows and not on others.  My first thought was that those fields must have been empty for those records, but then I re-read your description and it sounds like you've verified that those records _do_ contain data in those fields.

I've not encountered this problem, but I'm probably working with an ideal data set that may not reflect real-world scenarios.  This is kind of a light week at work for me.  I'll try to get permission to set up a sandbox on our dev server for this and actually run it with real-world data.  If not, then I can probably generate some real-world data from another application that I develop.  Hopefully I'll be able to reproduce the problem.

**Comment by DavidACameron-USDA** [comment]
Someone in systems is going to set up a sandbox for me.  That's the good news.  The bad news is that our need for this module is ending, apparently.  That's... annoying.  I'll keep working on it, but it sounds like I'm not going to be using it for my own job.

**Comment by sylus** [comment]
Ah so sorry to hear that! At least for potential future projects you now have this. Additionally I will be using for a rather high profile project so your work on this is most definitely appreciated! :)

**Comment by sylus** [comment]
I printed the id and it looks like it is related to language contexts as there are 3 variations of same id:

```
Organization: Agriculture and Agri-Food Canada
Year: 2016
Month: March
686e27b8018a9c3e6f419a726f363455en

Organization: ss_ati_organization_en [ss_ati_organization_en]: indexed as type text (boost 1)
Year: ss_ati_year_en [ss_ati_year_en]: indexed as type text (boost 1)
Month: ss_ati_monthname_en [ss_ati_monthname_en]: indexed as type string
686e27b8018a9c3e6f419a726f363455fr

Organization: Agriculture and Agri-Food Canada
Year: 2016
Month: March
686e27b8018a9c3e6f419a726f363455
```

So once I added a ss_language filter works as expected. I guess there is already some native language handling which is why the french fields weren't assigned a value?

Nonetheless I think this means everything is working as expected. 

Thank you so much!
